/* SPDX-License-Identifier: Apache-2.0 */

#ifndef SM2ECQV_SERVICE_H
#define SM2ECQV_SERVICE_H

#include "../sm2_pki_service.h"

typedef sm2_pki_service_ctx_t SM2_PKI_SERVICE_CTX;
typedef sm2_pki_error_t SM2_PKI_ERROR;

#define SM2_PKI_service_init sm2_pki_service_init
#define SM2_PKI_service_cleanup sm2_pki_service_cleanup
#define SM2_PKI_service_get_ca_public_key sm2_pki_service_get_ca_public_key
#define SM2_PKI_service_set_cert_field_mask sm2_pki_service_set_cert_field_mask
#define SM2_PKI_identity_register sm2_pki_identity_register
#define SM2_PKI_cert_request sm2_pki_cert_request
#define SM2_PKI_cert_issue sm2_pki_cert_issue
#define SM2_PKI_service_revoke_cert sm2_pki_service_revoke_cert
#define SM2_PKI_revoke_check sm2_pki_revoke_check
#define SM2_PKI_service_build_ocsp_cfg sm2_pki_service_build_ocsp_cfg

#endif
